library("dplyr")
library("knitr")
library("ggplot2")
library("leaflet")
library("shiny")
setwd("~/Desktop/HappyTreeFriends-201-Final-Project/YizhouDing")
source("my_ui.R")
source("my_server.R")

shinyApp(ui = my_ui, server = my_server)